In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [5]:
df = pd.read_csv('Data/insurance.csv')

In [9]:
pd.DataFrame(df)

       age     sex     bmi  children smoker     region      charges
0     19.0     NaN  27.900         0    yes  southwest  16884.92400
1     18.0    male  33.770         1     no  southeast   1725.55230
2     28.0    male  33.000         3     no  southeast   4449.46200
3     33.0    male  22.705         0     no  northwest  21984.47061
4     32.0    male  28.880         0     no  northwest   3866.85520
...    ...     ...     ...       ...    ...        ...          ...
1433  24.0    male  19.500         5    yes  southwest  45255.58000
1434  26.0  female  24.200         4     no  southwest   4181.43000
1435  41.0  female  33.600         5     no  northeast  15486.23000
1436  18.0    male  33.000         1     no  northeast  47619.75000
1437  61.0  female  22.700         1     no  northwest  44732.66000

[1438 rows x 7 columns]

In [25]:
df.head()

    age   sex     bmi  children smoker     region      charges
0  19.0  male  27.900         0    yes  southwest  16884.92400
1  18.0  male  33.770         1     no  southeast   1725.55230
2  28.0  male  33.000         3     no  southeast   4449.46200
3  33.0  male  22.705         0     no  northwest  21984.47061
4  32.0  male  28.880         0     no  northwest   3866.85520

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1438 entries, 0 to 1437
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1367 non-null   float64
 1   sex       1367 non-null   object
 2   bmi       1367 non-null   float64
 3   children  1438 non-null   int64
 4   smoker    1438 non-null   object
 5   region    1367 non-null   object
 6   charges   1438 non-null   float64
dtypes: float64(3), int64(1), object(3)
memory usage: 78.8+ KB

In [12]:
df.describe()

               age          bmi     children       charges
count  1367.000000  1367.000000  1438.000000   1438.000000
mean     39.389905    30.466240     1.197497  14263.806370
std      14.025264     6.177811     1.307840  12869.081884
min      18.000000    15.000000     0.000000   1121.873900
25%      27.000000    26.030000     0.000000   4908.572200
50%      40.000000    30.250000     1.000000   9794.877050
75%      51.000000    34.457500     2.000000  19135.377290
max      64.000000    53.130000     5.000000  63770.428010

In [13]:
#Target Variable = charges
#feautre Variables = age, bmi, smoker, children, smoker

In [28]:
#checking for missing values
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [16]:
df['age'] = df['age'].fillna(df['age'].median())

In [20]:
df['sex'] = df['sex'].fillna(df['sex'].mode()[0])

In [22]:
df['bmi'] = df['bmi'].fillna(df['bmi'].median())

In [27]:
df['region'] = df['region'].fillna(df['region'].mode()[0])

In [31]:
df = pd.get_dummies(df, columns=['sex'])